name: CrazeScoreboard
main: me.craze.csb.CrazeScoreboard
version: 1.0
api-version: 1.20
author: Mehetab
depend: [PlaceholderAPI, Vault]
commands:
  csb:
    description: Main command for CrazeScoreboard
    usage: /csb reload
permissions:
  crazescoreboard.use:
    description: Allows using scoreboard
    default: true
  crazescoreboard.reload:
    description: Allows reloading the plugin
    default: op
